### ISSUE TITLE
White spaces are removed when the docx template pages is generated with loops

### ISSUE THREAD

**Issue by adindariztia** [egonl/SharpDocx#58]
Hi, im trying to generate a document with repeated pages according to how many objects are in the model. However, when compiled, the extra spaces used to format the pages are missing. The docx template looks like this:

<%foreach (var m in Model.Cats) { %>
SOME_TITLE
<space>
SOME SUBTITLE
<space>
Name : <%= m.Name %>
SOME PARAGRAPH
<page break>
<% } %>

Ideally I should have something like this:
page1:
SOME_TITLE
<space>
SOME SUBTITLE
<space>
Name : Cat1
SOME PARAGRAPH

page 2:
SOME_TITLE
<space>
SOME SUBTITLE
<space>
Name : Cat2
SOME PARAGRAPH

but instead, all the spaces are removed and the generated document is like this:
page 1:
SOME_TITLE
SOME SUBTITLE
Name : Cat1
SOME PARAGRAPH

page 2:
SOME_TITLE
SOME SUBTITLE
Name : Cat2
SOME PARAGRAPH

I noticed that this problem is similar to issue [36](https://github.com/egonl/SharpDocx/issues/36) but it only handles page breaks and not spaces/new lines. Note that the same template without the loop can preserve these spaces, Im not sure why

**Comment by egonl** [comment]
If you mean new lines by 'white space', then that's intentional. New lines around code blocks are removed, see the DocumentBase.RemoveEmptyParagraphs method. Use Word paragraph spacing before and after a paragraph to format (and preserve white space around) paragraphs.

If you want you could try a new line with just a space: that shouldn't be deleted by the RemoveEmptyParagraphs  method.

**Comment by adindariztia** [comment]
Yes, that is what i meant. Tried that and it definitely solves the problem. I'll keep in mind to use the paragraph spacing instead of the new line/space in my docx. Thank you, super helpful!!
