### ISSUE TITLE
Possibility to generate complex tables

### ISSUE THREAD

**Issue by AlexAbd1990** [egonl/SharpDocx#72]
Hello! My task is to make a table showing one-to-many relationship. It should look like this:

![image](https://github.com/egonl/SharpDocx/assets/47560377/679f2c43-3a97-476f-9705-ce4192d05967)

The model I am using for an example:

![image](https://github.com/egonl/SharpDocx/assets/47560377/a3e559c9-649d-4277-9ad0-37e2e6738e37)

As you can see, I need a table with merged cells.
I spent a long time trying to figure out how I could generate such a table. But all I was able to do is these two options (the first screenshot is the template file, the second is the result of the generation):
[TEMPLATE ([Teams.cs.docx](https://github.com/egonl/SharpDocx/files/15205196/Teams.cs.docx))]
![image](https://github.com/egonl/SharpDocx/assets/47560377/89b79730-f487-4c6a-9dc5-60f6e9333528)
[RESULT]
![image](https://github.com/egonl/SharpDocx/assets/47560377/41cbd824-7eed-44b9-b3df-e8085a938c42)

Can you tell me if it is possible to make the table I need at all. And if so, what am I doing wrong?
P.S. Thanks for this project, it's very handy and cool!

**Comment by egonl** [comment]
Don't mix AppendRow with text blocks, but use Write instead. This might be the easiest approach:

![image](https://github.com/egonl/SharpDocx/assets/34315684/5bbe3e5a-f3bc-4796-a3df-112574fcdfeb)

It's not exactly what it should look like, but it's close. Doing it exactly is complicated, since you would need to insert table cells - which is not supported out of the box.

**Comment by AlexAbd1990** [comment]
Thx for your answer
